export const IS_LOADING = "IS_LOADING";

// Auth
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";
export const SIGNIN_WITH_GOOGLE_SUCCESS = "SIGNIN_WITH_GOOGLE_SUCCESS";
export const SIGNIN_WITH_GOOGLE_FAILURE = "SIGNIN_WITH_GOOGLE_FAILURE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILURE = "SIGNOUT_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
